Mathi27/ErrorHunter

- problems/easy/easy_q1.py
This is Mirdula R from CSE Cyber Security department. The division is changed to Modulus in line of the code.
> Odd or Even_program1

- problems/medium/m1.py
Iam S.R praneash shiva of Cyber security. i have added expontential operation and solved the problem of the code. The problem of the code is the function was not called and i have added some add-ons.
> Mathematical operation menu

- problems/medium/m17.py
- problems/medium/m9.py
FIXES IN m9.py:
This program is about the set operations . The bug in this program ,is the set operations are not correctly performed . The set operations are *(| union) *(& Intersection) *(- Difference)*(<= subset) which should be used  in this program , was wrongly placed and missing symbol . Which i was corrected
FIXES IN m17.py
In the line 4 there is a bug , to reverse a list or string negative indexing should be used . The starting index should be -1 and the ending index should be -(length of the list) which was missing in the program, that i corrected
> FIX : bugs in m9.py  and m17.py

- problems/easy/easy_q1.py
- problems/easy/easy_q2.py
- problems/easy/easy_q3.py
- problems/easy/easy_q4.py
- problems/easy/easy_q5.py
1.corrected by / to %
2.return value is changed and in line 10 num1 is changed to num2
3.corrected by changing the leap year
4.string is converted to integer and proper print statement
5.string is converted to integer
> changes made successfully

- problems/easy/easy_q2.py
- problems/easy/easy_q3.py
- problems/easy/easy_q5.py
> error identify

- problems/easy/easy_q1.py
- problems/easy/easy_q2.py
- problems/easy/easy_q3.py
> Opensource

- problems/medium/m10.py
- problems/medium/m15.py
- problems/medium/m2.py
- problems/medium/m8.py
The logical error is rectified
> Armstrong Numbers

- problems/easy/easy_q1.py
- problems/easy/easy_q10.py
i have rectified the logical error
> odd or even

- problems/medium/m1.py
- problems/medium/m10.py
- problems/medium/m11.py
In m10 , there were some of the games and in m11 , we can calculate perimeter , area , of many shapes which has some errors 
With a patience the errors are deducted and debugged in a right and efficient manner .
(My first pull request as a collaborator , thank you!!)
> Debugging m10 and m11 with patience

- problems/medium/m17.py
The given contained some logical error like invalid access of index etc. This code solved all these errors and made the code to run
> Reverse of a list

- problems/easy/easy_q2.py
- problems/easy/easy_q3.py
- problems/easy/easy_q4.py
the required changes are made in the python code to accept a number and check if the number is positive or negative or zero
> positive negative or zero

- problems/medium/m15.py
i have Modified Armstrong Number in Simple way
> Modified Armstrong Numbers

- FunProjects/todoApp.py
used if condition with for loop.
used function to remove and display list.
> ToDoApp is solved

- FunProjects/rockPaperSiss.py
- problems/medium/m15.py
- problems/medium/m17.py
> RockPaperScissors

- FunProjects/directions.py
- FunProjects/snakeLadder.py
- problems/hard/PET.py
Actually there was a critical error in tha code where the while loop condition so the loop executed above the limit so, i altered that and there were one ladder and one snake , so i decided to add more using dictionary, and made user friendly , by clicking the enter key, dice will roll and the rest will carry on smoothly
> added some changes in Snake and Ladder

- FunProjects/directions.py
- problems/hard/PET.py
The Personal Expense Tracker code has been updated to include date validation to ensure correct input format (YYYY-MM-DD), error handling for JSON parsing to handle corrupted or empty files, and  improvement to the pie chart display to  the user if there are fewer than two expense categories. Better feedback and validation checks for valid index inputs and empty expenditure lists were also added to the remove method. error handling signals for incorrect inputs, the user experience enhanced overall, making the code easy to use.
> added Exceptional handling and corrected some logics

- problems/medium/m4.py
Check Prime
Factorial
Fibonacci Sequence
Sum of Digits
> adding a title in to program for menu

- problems/medium/m2.py
- problems/medium/m3.py
we check palindrome and invalid input re arrange and empty string
> String Manipulation Tool

- problems/easy/easy_q12.py
I Changed the indentationError
> Change in calculater

- problems/easy/easy_q11.py
- problems/easy/easy_q13.py
- problems/easy/easy_q14.py
- problems/easy/easy_q15.py
- problems/easy/easy_q17.py
- problems/easy/easy_q18.py
- problems/easy/easy_q4.py
- problems/easy/easy_q5.py
- problems/easy/easy_q7.py
- problems/medium/m1.py
- problems/medium/m2.py
- problems/medium/m3.py
> Open -Source contribution by Sanjay

- problems/easy/easy_q1.py
- problems/easy/easy_q11.py
- problems/easy/easy_q13.py
- problems/easy/easy_q15.py
- problems/easy/easy_q4.py
- problems/easy/easy_q5.py
- problems/easy/easy_q6.py
- problems/easy/easy_q7.py
- problems/easy/easy_q8.py
- problems/medium/m1.py
- problems/medium/m3.py
- problems/medium/m5.py
> open source contribution by abhiram

- FunProjects/NumberGuess.py
- problems/easy/easy_q1.py
- problems/easy/easy_q10.py
- problems/easy/easy_q13.py
- problems/easy/easy_q14.py
- problems/easy/easy_q15.py
- problems/easy/easy_q16.py
- problems/easy/easy_q17.py
- problems/easy/easy_q18.py
- problems/easy/easy_q2.py
- problems/easy/easy_q3.py
- problems/easy/easy_q4.py
- problems/easy/easy_q6.py
- problems/easy/easy_q7.py
- problems/hard/PET.py
- problems/medium/m1.py
- problems/medium/m11.py
- problems/medium/m2.py
- problems/medium/m3.py
- problems/medium/m6.py
- problems/medium/m9.py
i have debugged the errors of 13 files and changed the codes
> Boomika S N 

- problems/medium/m2.py
- problems/medium/m7.py
> error rectified

- FunProjects/arrayCompare.py
- FunProjects/rockPaperSiss.py
- problems/easy/easy_q1.py
- problems/medium/m1.py
- problems/medium/m10.py
- problems/medium/m2.py
- problems/medium/m3.py
Errors like importing libraries ,calling a function, taking proper input has been resolved.
> Basic concept errors has been rectified.

- problems/easy/easy_q1.py
- problems/easy/easy_q2.py
- problems/medium/m1.py
- problems/medium/m2.py
- problems/medium/m3.py
- problems/medium/m4.py
- problems/medium/m5.py
- problems/medium/m7.py
I corrected various logical errors and enhanced the code
> My Contributions-Shakthi Rithanya S

- FunProjects/NumberGuess.py
- problems/easy/easy_q1.py
- problems/easy/easy_q2.py
- problems/easy/easy_q3.py
- problems/easy/easy_q4.py
- problems/easy/easy_q5.py
- problems/easy/easy_q6.py
- problems/easy/easy_q7.py
- problems/easy/easy_q8.py
- problems/medium/m1.py
easy:
1.required changes to check if a number is odd or even 
2.changes required to find the largest of 2 numbers
3.changes required to check if a year is leap year 
4.changes required to find positive,negative and 0 from a number entered
to print numbers from 1 to 10
5.changes required to find a student's grade
medium:
1.changes required in a simple maths operators.
> solved problems from 1 to 6 and one in medium 

- problems/easy/easy_q1.py
- problems/easy/easy_q10.py
- problems/easy/easy_q11.py
- problems/easy/easy_q12.py
- problems/easy/easy_q13.py
- problems/easy/easy_q14.py
- problems/easy/easy_q15.py
- problems/easy/easy_q16.py
- problems/easy/easy_q17.py
- problems/easy/easy_q18.py
- problems/easy/easy_q2.py
- problems/easy/easy_q3.py
- problems/easy/easy_q4.py
- problems/easy/easy_q5.py
- problems/easy/easy_q6.py
- problems/easy/easy_q7.py
- problems/easy/easy_q8.py
- problems/easy/easy_q9.py
This is Jeffrey Shalom from CSE A modified the codes. Please check
> Modified questions

- problems/easy/easy_q1.py
- problems/medium/m2.py
Zuvairiya shifa cybersecurity . fixed error in operator ,that is / to % in line 4
> expression error

- problems/easy/easy_q1.py
resolving the  issues in odd or even problem
> resolving the pug

- problems/easy/easy_q1.py
- problems/easy/easy_q2.py
- problems/easy/easy_q3.py
- problems/easy/easy_q4.py
- problems/easy/easy_q5.py
- problems/easy/easy_q6.py
- problems/easy/easy_q7.py
- problems/easy/easy_q8.py
- problems/easy/easy_q9.py
- problems/medium/m1.py
> resolving pug

- FunProjects/AtmMachineSimulator.py
- FunProjects/arrayCompare.py
- problems/easy/easy_q1.py
- problems/easy/easy_q18.py
- problems/easy/easy_q2.py
- problems/easy/easy_q3.py
- problems/easy/easy_q4.py
- problems/easy/easy_q5.py
- problems/medium/m10.py
- problems/medium/m17.py
- problems/medium/m4.py
The issue of this code was resolved and error handling was included. So, that any other data types except integer won't be accepted.
> The issue of this code was resolved and error handling was included

- problems/easy/easy_q1.py
- problems/easy/easy_q10.py
- problems/easy/easy_q11.py
- problems/easy/easy_q12.py
- problems/easy/easy_q13.py
- problems/easy/easy_q14.py
- problems/easy/easy_q15.py
- problems/easy/easy_q16.py
- problems/easy/easy_q17.py
- problems/easy/easy_q18.py
- problems/easy/easy_q2.py
- problems/easy/easy_q3.py
- problems/easy/easy_q4.py
- problems/easy/easy_q5.py
- problems/easy/easy_q6.py
- problems/easy/easy_q7.py
- problems/easy/easy_q8.py
- problems/easy/easy_q9.py
- problems/medium/m1.py
I find out two easy questions. I just tried out to pull request
> odd or even and largest of two

- FunProjects/NumberGuess.py
- problems/medium/m13.py
Error handling is fixed and also fixed other bugs.
> Fixed m1 and m13.py

- problems/easy/easy_q1.py
- problems/medium/m10.py
- problems/medium/m13.py
CODE HAS ERROR IN ROCK ,PAPER,SCISSORS LOGIC AND  SYNTAX ERROR .WE HAVE BEEN MODFIED THE LOGIC ERROR WITH DIFFFERENT METHOD AND SYNTAX ERROR. THANK YOU
> M10 Has Been Modified By AIML Boys
